version: "3"

vars:
  FLUTTER_DIR: "{{.ROOT_DIR}}/flutter_app"
  LEGACY_ANDROID_DIR: "{{.ROOT_DIR}}/android"
  LEGACY_GRADLE_FILE: "{{.LEGACY_ANDROID_DIR}}/app/build.gradle.kts"
  LEGACY_AAB_OUTPUT: "{{.LEGACY_ANDROID_DIR}}/app/build/outputs/bundle/release/app-release.aab"
  LEGACY_APK_OUTPUT: "{{.LEGACY_ANDROID_DIR}}/app/build/outputs/apk/debug/app-debug.apk"

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  flutter:pub:
    desc: Install Flutter dependencies
    dir: "{{.FLUTTER_DIR}}"
    cmds:
      - flutter pub get

  flutter:analyze:
    desc: Run Flutter static analysis
    dir: "{{.FLUTTER_DIR}}"
    cmds:
      - flutter analyze

  flutter:test:
    desc: Run Flutter tests
    dir: "{{.FLUTTER_DIR}}"
    cmds:
      - flutter test

  flutter:run:
    desc: Run Flutter app
    dir: "{{.FLUTTER_DIR}}"
    cmds:
      - flutter run

  flutter:build:apk:
    desc: Build Flutter Android APK (release)
    dir: "{{.FLUTTER_DIR}}"
    cmds:
      - flutter build apk --release

  flutter:build:aab:
    desc: Build Flutter Android App Bundle (release)
    dir: "{{.FLUTTER_DIR}}"
    cmds:
      - flutter build appbundle --release

  flutter:clean:
    desc: Clean Flutter build artifacts
    dir: "{{.FLUTTER_DIR}}"
    cmds:
      - flutter clean

  legacy:build:
    desc: Build debug APK for legacy Hotwire Android app
    dir: "{{.LEGACY_ANDROID_DIR}}"
    cmds:
      - ./gradlew assembleDebug
      - echo "Debug APK -> {{.LEGACY_APK_OUTPUT}}"

  legacy:build:release:
    desc: Build release AAB for legacy Hotwire Android app
    dir: "{{.LEGACY_ANDROID_DIR}}"
    preconditions:
      - sh: test -f {{.LEGACY_ANDROID_DIR}}/keystore.properties
        msg: "keystore.properties not found. See scripts/build-release.sh for format."
    cmds:
      - ./gradlew bundleRelease
      - echo "Release AAB -> {{.LEGACY_AAB_OUTPUT}}"

  legacy:version:
    desc: Show legacy Hotwire Android version
    cmds:
      - |
        CODE=$(sed -n 's/.*versionCode = \([0-9]*\)/\1/p' {{.LEGACY_GRADLE_FILE}})
        NAME=$(sed -n 's/.*versionName = "\([^"]*\)"/\1/p' {{.LEGACY_GRADLE_FILE}})
        echo "Version: $NAME (code: $CODE)"

  legacy:clean:
    desc: Clean legacy Hotwire Android build outputs
    dir: "{{.LEGACY_ANDROID_DIR}}"
    cmds:
      - ./gradlew clean
