version: "3"

vars:
  ANDROID_DIR: "{{.ROOT_DIR}}/android"
  GRADLE_FILE: "{{.ANDROID_DIR}}/app/build.gradle.kts"
  AAB_OUTPUT: "{{.ANDROID_DIR}}/app/build/outputs/bundle/release/app-release.aab"
  APK_OUTPUT: "{{.ANDROID_DIR}}/app/build/outputs/apk/debug/app-debug.apk"

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  build:
    desc: Build debug APK
    dir: "{{.ANDROID_DIR}}"
    cmds:
      - ./gradlew assembleDebug
      - echo "Debug APK -> {{.APK_OUTPUT}}"

  build:release:
    desc: Build release AAB (no version bump)
    dir: "{{.ANDROID_DIR}}"
    preconditions:
      - sh: test -f {{.ANDROID_DIR}}/keystore.properties
        msg: "keystore.properties not found. See scripts/build-release.sh for format."
    cmds:
      - ./gradlew bundleRelease
      - echo "Release AAB -> {{.AAB_OUTPUT}}"

  release:
    desc: Bump version and build release AAB
    cmds:
      - ./scripts/build-release.sh

  version:
    desc: Show current version
    cmds:
      - |
        CODE=$(sed -n 's/.*versionCode = \([0-9]*\)/\1/p' {{.GRADLE_FILE}})
        NAME=$(sed -n 's/.*versionName = "\([^"]*\)"/\1/p' {{.GRADLE_FILE}})
        echo "Version: $NAME (code: $CODE)"

  clean:
    desc: Clean build outputs
    dir: "{{.ANDROID_DIR}}"
    cmds:
      - ./gradlew clean
